$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: sample_pytorch_gpu_pipeline_run  # change this name each run to be descriptive
experiment_name: sample_pytorch_gpu_pipeline
description: Pytorch model training, inference, evaluation.

jobs:
  train_component:
    type: command
    component: /workspace/src/sample_pytorch_gpu_project/aml_components/train-component.yaml
    compute: azureml:pytorch-gpu-cluster
    inputs:
      data_dir:
        type: uri_folder
        path: azureml://datastores/split_data_datastore/paths/3class_labels_iter01/
        mode: download
    outputs:
      train_artifacts_dir: 
        type: uri_folder
        mode: rw_mount
  inference_component:
    type: command
    component: /workspace/src/sample_pytorch_gpu_project/aml_components/inference-component.yaml
    compute: azureml:pytorch-gpu-cluster
    inputs:
      data_dir:
        type: uri_folder
        path: azureml://datastores/split_data_datastore/paths/3class_labels_iter01/
        mode: download
      train_artifacts_dir: ${{parent.jobs.train_component.outputs.train_artifacts_dir}}
    outputs:
      test_set_preds_dir: 
        type: uri_folder
        mode: rw_mount
  evaluate_component:
    type: command
    component: /workspace/src/sample_pytorch_gpu_project/aml_components/evaluate-component.yaml
    compute: azureml:pytorch-cpu-cluster 
    inputs:
      metadata_csv:
        type: uri_file
        path: azureml://datastores/split_data_datastore/paths/3class_labels_iter01/test/test_metadata.csv
        mode: download
      inference_preds_dir: ${{parent.jobs.inference_component.outputs.test_set_preds_dir}}
identity:  # see README for detailed instructions on auth options and setup
  # use with a managed identity assigned to compute cluster
  # type: managed_identity
  # use with user identity that is logged in to AML CLI
  type: user_identity