# Azure DevOps CI Pipeline (Self-Hosted Agent)
#
# This pipeline runs on self-hosted agents and supports both Linux and macOS (Apple Silicon).
# Templates are located in .azuredevops/templates/

trigger:
  - main

stages:
  # - stage: Lint
  #   displayName: 'Lint'
  #   jobs:
  #     - job: RunLinter
  #       displayName: 'Run ruff linter'
  #       pool:
  #         name: Default
  #       workspace:
  #         clean: all
  #       steps:
  #         - script: |
  #             python3 -m venv venv
  #             source venv/bin/activate
  #             pip install --upgrade pip
  #             pip install -r requirements-dev.txt
  #           displayName: 'Install requirements'
  #
  #         - bash: |
  #             source venv/bin/activate
  #             ruff check --output-format azure
  #           displayName: 'Run ruff linter'

  - stage: Test
    displayName: 'Test Devcontainers'
    jobs:
      - template: templates/test-devcontainer-job.yml
        parameters:
          projects:
            - name: 'cpu-project'
              configPath: 'src/sample_cpu_project/.devcontainer/devcontainer.json'
              projectPath: 'src/sample_cpu_project'
            - name: 'gpu-project'
              configPath: 'src/sample_pytorch_gpu_project/.devcontainer/devcontainer.json'
              projectPath: 'src/sample_pytorch_gpu_project'
            - name: 'notebooks'
              configPath: 'notebooks/.devcontainer/devcontainer.json'
              projectPath: 'notebooks'
              smokeTestOnly: true
          pool:
            name: Default

      - job: PublishCoverage
        displayName: 'Publish Coverage'
        dependsOn: [Test_cpu_project, Test_gpu_project, Test_notebooks]
        condition: succeededOrFailed()
        pool:
          name: Default
        steps:
          - template: templates/merge-coverage.yml
            parameters:
              coverageArtifacts:
                - 'coverage-cpu-project'
                - 'coverage-gpu-project'
