# Azure DevOps pipeline for CI (Microsoft-hosted version)
# As the Microsoft-hosted agent option has a limit of 10GB of storage for disk outputs from a pipeline,
# this causes an issue when the Docker images for modules under src require more than 10GB of storage.
# If you will run into space issues (or other limitations with a Microsoft hosted agent option outlined in
# https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#capabilities-and-limitations),
# consider using the .azuredevops/ado-ci-pipeline-self-hosted.yml version or using scale set agents, see
# this link for more info: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
# Note that docker images will only be build for src directories that contain at least one test file, so the
# total space consumed by Docker builds will be dependent on which modules under src contain tests.
# For setting up the pipeline in ADO see:
# https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser
#
# Templates are located in .azuredevops/templates/

trigger:
  - main

stages:
  - stage: Lint
    displayName: 'Lint'
    jobs:
      - job: RunLinter
        displayName: 'Run ruff linter'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.11'
            inputs:
              versionSpec: 3.11

          - script: |
              python -m venv venv
              source venv/bin/activate
              python -m pip install --upgrade pip
              pip install -r requirements-dev.txt
            displayName: 'Install requirements'

          - bash: |
              source venv/bin/activate
              ruff check --output-format azure
            displayName: 'Run ruff linter'

  - stage: Test
    displayName: 'Test Devcontainers'
    jobs:
      - template: templates/test-devcontainer-job.yml
        parameters:
          projects:
            - name: 'cpu-project'
              configPath: 'src/sample_cpu_project/.devcontainer/devcontainer.json'
              projectPath: 'src/sample_cpu_project'
            - name: 'gpu-project'
              configPath: 'src/sample_pytorch_gpu_project/.devcontainer/devcontainer.json'
              projectPath: 'src/sample_pytorch_gpu_project'
            - name: 'notebooks'
              configPath: 'notebooks/.devcontainer/devcontainer.json'
              projectPath: 'notebooks'
              smokeTestOnly: true
          pool:
            vmImage: 'ubuntu-latest'

      - job: PublishCoverage
        displayName: 'Publish Coverage'
        # NOTE: test-devcontainer-job.yml creates one job per project with the name pattern:
        #   Test_<project-name-with-hyphens-replaced-by-underscores>
        # For the projects defined above:
        #   - cpu-project     -> Test_cpu_project
        #   - gpu-project     -> Test_gpu_project
        #   - notebooks       -> Test_notebooks
        # If you change a project name, update the corresponding entry here to match this convention.
        dependsOn: [Test_cpu_project, Test_gpu_project, Test_notebooks]
        condition: succeededOrFailed()
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: templates/merge-coverage.yml
            parameters:
              coverageArtifacts:
                - 'coverage-cpu-project'
                - 'coverage-gpu-project'
