version: '3'
services:
  notebooks:
    env_file: ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ../..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
