# Github Actions Workflow for CI

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Run ruff linter
        run: |
          uvx ruff check --output-format github

      - name: Run pytest in docker containers
        run: ./ci-tests.sh
        env:
          BUILD_ARTIFACTSTAGINGDIRECTORY: ${{ github.workspace }}

      - name: Publish Test Results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: pytest
          path: |
            **/test-results-*.xml
          reporter: java-junit

      - name: Publish Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          badge: true
          output: both
          format: markdown
          filename: coverage.xml

      - name: Add code coverage summary markdown to github step summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Archive test and code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-and-coverage-results
          path: |
            **/test-reuslts-*.xml
            coverage.xml
